<?php
define("EVIDENCE_META_BOX","WP_BADGER_EXTENDED_META_EVIDENCE");
define("CRITERIA_META_BOX","WP_BADGER_EXTENDED_META_CRITERIA");
//define("EMAIL_META_BOX","WP_BADGER_EXTENDED_META_CRITERIA");

?>